### ISSUE TITLE
ダウンロードフォントがダウンロードできない環境でクラッシュした

### ISSUE THREAD

**Issue by NUmeroAndDev** [NUmeroAndDev/SojoDia-android#50]
## 条件  
* 電波オフ  
* アップデート後初回起動

以下のメッセージでクラッシュする  
```
java.lang.NullPointerException: Attempt to read from field 'int android.support.v4.provider.FontsContractCompat$TypefaceResult.mResult' on a null object reference
                                                                        at android.support.v4.provider.FontsContractCompat$2.onReply(FontsContractCompat.java:277)
                                                                        at android.support.v4.provider.FontsContractCompat$2.onReply(FontsContractCompat.java:274)
                                                                        at android.support.v4.provider.FontsContractCompat$3.onReply(FontsContractCompat.java:312)
                                                                        at android.support.v4.provider.FontsContractCompat$3.onReply(FontsContractCompat.java:300)
                                                                        at android.support.v4.provider.SelfDestructiveThread$2$1.run(SelfDestructiveThread.java:149)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:224)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5526)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by NUmeroAndDev** [comment]
[SupportLibrary 27.1.0](https://developer.android.com/topic/libraries/support-library/revisions.html) に上げるとクラッシュ問題が修正されたっぽいから、ライブラリを更新してからダウンロードフォントを使用する。
